import type { BusinessProfile } from "../../shared/types.js";

/**
 * Generate the source of the site's `src/content.ts` from a business profile.
 * Deterministic — no model call. The first build uses this; the codegen agent
 * edits the resulting file afterward for content and colour changes.
 */
export function profileToContentSource(profile: BusinessProfile): string {
  const json = JSON.stringify(profile, null, 2);
  return `// AUTO-GENERATED by @chasm/codegen on first build.
// The site renders from this object. The codegen agent edits this file for
// content / colour changes, and components for layout changes.
export const content = ${json} as const;

export type SiteContent = typeof content;
`;
}
